# **Marco Guanchez Week 5 Homework**

### 7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_reshaped = arr.reshape((2,3,2))
print(arr_reshaped)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### 8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20


In [19]:
array1 = np.linspace(0,20,6)
print(array1)

[ 0.  4.  8. 12. 16. 20.]


### 9. Make a Deep Copy of the above array

In [23]:
import numpy as np
array1 = np.linspace(0, 20, 6)
deep_copy_arr = np.copy(array1)
print(deep_copy_arr)

[ 0.  4.  8. 12. 16. 20.]


### 10. Concatenate these 3 arrays into a new array named 'newArray'...  
        ([[25, 16]])  
        ([[11, 2], [13, 4]])  
        ([[7, 81], [5, 6], [11, 12]])  


In [31]:
import numpy as np

arraya = np.array([[25, 16]])
arrayb = np.array([[11, 2], [13, 4]])  
arrayc = np.array([[7, 81], [5, 6], [11, 12]])

newarray = np.concatenate(( arraya,arrayb,arrayc), axis=0)
print(newarray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


#### 11. Sort 'newArray' in order into 'sortedArray'


In [33]:
import numpy as np
sortedarray = np.sort(newarray)
print(sortedarray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


### 12. Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.


In [56]:
reshapedArray = [(0, 1, 2), (3, 4, 5), (6, 7, 8), (9, 10, 11)]
vara, varb, varc, vard = zip(reshapedArray)
print(vara)
print(varb)
print(varc)
print(vard)



((0, 1, 2),)
((3, 4, 5),)
((6, 7, 8),)
((9, 10, 11),)


### 13. Combined and sort the following arrays into one called 'comboArray' ...  
    one = ([10, 11, 12, 13, 14, 15, 16, 17])  
    two = ([20, 21, 22, 23, 24, 25, 26, 27])  
    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])  


In [59]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = sorted (one + two + three)
print("comboArray:", comboarray)

comboArray: [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]


### 14. Take 'comboArray' and perform the following slicing activities:

* print sec1 - the 2nd element  
* print sec2 - all elements from the 3rd element to the last  
* print sec3 - all elements from the 4th to the 14th elements  
* print sec4 - the last 6 elements  
* print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.  
* print sec6 - from #20 every even element to the end  
* print sec7 - from the last element moving forward, every 5th element.  

In [76]:
import numpy as np
# print sec1 - the 2nd element  
sec1 = comboArray[1]
print("The 2nd element is:", sec1)
sec2 = comboArray[2:]
print ("From the 3rd element to the last:", sec2)
sec3 = comboArray[3:14]
print("From the 4th element to the 14th", sec3)
sec4 = comboArray[-6:]
print("The last six elements are:", sec4)
sec5 = comboArray[-24:-10]
print("From zero to 15th element", sec5)
sec6 = comboArray[16::2]
print("From 20 every even element to the end", sec6)
sec7 = comboArray[::-5]
print("From the last element moving forward, every 5th element", sec7)

The 2nd element is: 1
From the 3rd element to the last: [2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25, 26, 27]
From the 4th element to the 14th [3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]
The last six elements are: [22, 23, 24, 25, 26, 27]
From zero to 15th element [0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14, 15]
From 20 every even element to the end [20, 22, 24, 26]
From the last element moving forward, every 5th element [27, 22, 15, 10, 3]


### 15. Using Series, create a DataFrame that looks like this:  

Ingredients	Quantity	Unit  
Flour	    4	        cups  
Milk	    1	        cup  
Eggs	    2	        large  
Spam	    1	        can  
Name: Dinner, dtype: object  


In [93]:
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Ingredients')
quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
unit =  pd.Series(['cups', 'cup', 'large', 'can'], name = 'Unit')

dataframe= pd.concat([ingredients, quantity, unit], axis=1)
print(dataframe)




  Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


### 16. Take this data and create a DataFrame named studentData
    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }


In [103]:

students = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'Address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(Student)

print(studentData)


      Name  Height Qualification  Address  Age        Pets           Sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


### 17. Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]



In [105]:
studentData['Desserts'] = ['ice cream', 'Cashe Fudge', 'waffels', "Carrot Halwa"]
print(studentData)

      Name  Height Qualification  Address  Age        Pets           Sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

       Desserts  
0     ice cream  
1   Cashe Fudge  
2       waffels  
3  Carrot Halwa  


### 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"


In [123]:
import pandas as pd

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'],
    'deserts': ['ice cream', 'Cashew Fudge', 'waffles', 'Carrot Halwa']
}
studentData = studentData.sort_values(by=['Name', 'address'], ascending=[True, True])

print(studentData)


      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        deserts  
3  Carrot Halwa  
2       waffles  
0     ice cream  
1  Cashew Fudge  


### 19. Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:


In [ ]:
df = pd.DataFrame({'Cows': [12,20], 'Goats': [22,19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

### 20.
### (A) Using Pandas, make your own .CSV file with data on vegetables and save it.
### (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

In [9]:
#(A) 
import pandas as pd

vegetable = pd.Series(['Jalapeno', 'Onion', 'Avocado', 'Pumpkin'], name = 'Vegetable')
color = pd.Series(['Green', 'Yellow', 'Green', 'Orange' ], name = 'Color')


df = pd.concat([vegetable, color], axis=1)

df.to_csv('vegetables.csv')

print(df)

#(B)
vegetablesNew = pd.read_csv('vegetables.csv')

uglypretty = pd.Series(['pretty', 'ugly', 'pretty', 'ugly'])

dfb = pd.concat([df, uglypretty])

dfb.to_csv('vegetables2.csv')

  Vegetable   Color
0  Jalapeno   Green
1     Onion  Yellow
2   Avocado   Green
3   Pumpkin  Orange
